name: wealth-finance-stack

services:
  analyz_corp_db:
    image: postgres:17
    container_name: wealth_finance_db
    restart: unless-stopped
    networks:
      - wealth_finance_internal
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_INITIAL_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      PGDATA: /var/lib/postgresql/data/pgdata
      APP_OW_USER: ${APP_OW_USER}
      APP_DB_NAME: ${APP_DB_NAME}
    volumes:
      #- postgres_data:/var/lib/postgresql/data/pgdata
      - ./init-scripts:/docker-entrypoint-initdb.d
    secrets:
      - db_password
      - app_ow_password
    user: "999:999"
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_INITIAL_USER:-postgres} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    driver: local

networks:
  wealth_finance_internal:
    driver: bridge
    name: wealth_finance_internal

secrets:
  db_password:
    file: ./secrets/postgres_password
  app_ow_password:
    file: ./secrets/app_ow_password
